export const Colours = {
  navActiveTint: "#828282",
  navActiveBackground: "#E5E5E5",
  navInactiveTint: "#BDBDBD",
  navInactiveBackground: "#ffffff",
  divider: "#CCC5C5",
  screenBackground: "#ffffff",
  borderedComponentFill: "#ffffff",
  switchButtonSelected: "#5A5A5A",
  switchButtonSelectedText: "#ffffff",
  switchButtonNotSelected: "#ffffff",
  switchButtonNotSelectedText: "#000000",
  filledButton: "#d8d8d8",
  tint: "#000000",
  listButton: "#DDDDDD",
  notice: "#BDBDBD",
};
