export const Colours = {
  navActiveTint: "#3C8A37",
  navActiveBackground: "#ffffff",
  navInactiveTint: "#BDBDBD",
  navInactiveBackground: "#ffffff",
  divider: "#CCC5C5",
  screenBackground: "#ffffff",
  borderedComponentFill: "#ffffff",
  switchButtonSelected: "#3C8A37",
  switchButtonSelectedText: "#ffffff",
  switchButtonNotSelected: "#ffffff",
  switchButtonNotSelectedText: "#3C8A37",
  filledButton: "#3C8A37",
  filledButtonText: "#ffffff",
  textInputBackground: "#EFEFEF",
  textInputPlaceholder: "#BDBDBD",
  toggleSliderSelected: "#a3d3cf",
  toggleSliderNotSelected: "#ffffff",
  toggleThumbSelected: "#009688",
  toggleThumbNotSelected: "#fafafa",
  recipeCardButton: "#B6B6B6",
  tint: "#60646D",
  notice: "#BDBDBD",
};
